### ISSUE TITLE
Invalid "csv" format, supported formats are : ""

### ISSUE THREAD

**Issue by dureimatlecam** [john-dufrene-dev/sonata-platform#6]
Hi John,
Thanks for your great work ! i really enjoy working on it.
i have a an error when i try to export, did you already have this issue ?
Thanks
Mathieu

**Comment by john-dufrene-dev** [comment]
This commit 12ff342b604d606726565f62c0bdae74feceea52 fix the error
Thanks @dureimatlecam for your contribution, I really enjoy it !
I try to create a complete default platform, if you want to help don't hesitate to purpose new feature :)

**Comment by dureimatlecam** [comment]
@john-dufrene-dev  thanks to you. I will be happy to purpose new feature.
This is a really good job ! i love using your platform :)

**Comment by dureimatlecam** [comment]
@john-dufrene-dev i think the big work is to go on SF5.

**Comment by john-dufrene-dev** [comment]
@dureimatlecam thanks for your comment, compatibility with SF5 is easy but for the moment prefer to add New functionnalities and fixe error, if you want you Can truc to dix sole error you fond in readme.md or another feature is to add translations in JS easy may be with a bundle or from scratch, all Idea is good you Can Do pull request if you want :)
